name: MoneyMAP updater

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: skynet

    steps:
    - name: Update Money MAP
      working-directory: /var/www/html/money_map
      run: |
        php artisan down
        git fetch origin main
        git reset --hard origin/main
        php artisan migrate
        php artisan db:seed
        composer dump-autoload
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        php artisan optimze 
        php artisan up
